name: Update NBA Database

on:
  schedule:
    # Runs daily at 3 AM UTC (adjust as needed)
    - cron: '0 3 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # Required to push changes back
        fetch-depth: 0  # Get all history for all branches
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Use your preferred version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests tqdm sqlite3
        
    - name: Run database update
      run: |
        cd NBA-Prediction
        python Database.py
        
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add docs/assets/c_nba_2025.db.gz
        git diff --quiet && git diff --staged --quiet || git commit -m "Automated database update [skip ci]"
        git push